INSERT INTO tables (table_id, capacity, location, status) 
VALUES 
(1, 10, 'Main Hall Left', 'available'),
(2, 10, 'Main Hall Right', 'available'),
(3, 10, 'Corner Window', 'available'),
(4, 10, 'VIP Lounge', 'available'),
(5, 4, 'Near Entrance', 'available'),
(6, 4, 'Patio', 'available'),
(7, 4, 'Balcony', 'available'),
(8, 4, 'Garden View', 'available'),
(9, 4, 'Center Floor', 'available'),
(10, 4, 'Near Kitchen', 'available'),
(11, 4, 'Back Wall', 'available'),
(12, 4, 'Fireplace Side', 'available'),
(13, 4, 'Beside Bar', 'available'),
(14, 4, 'Lounge Area', 'available'),
(15, 4, 'Private Booth', 'available'),
(16, 4, 'Terrace', 'available'),
(17, 4, 'Window Side', 'available'),
(18, 4, 'Quiet Zone', 'available'),
(19, 4, 'Near DJ Booth', 'available'),
(20, 4, 'Garden Corner', 'available');
